#!/bin/bash
echo '#include <stdio.h>\n\nint main(void)\n{\n    printf("with proper grammar, but the outcome is a piece of art,\\n");\n    return (0);\n}' > 5-printf.c && gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -o 5-printf 5-printf.c
